branch-defaults:
  master:
    environment: AyoServer-env-1
environment-defaults:
  AyoServer-env-1:
    branch: null
    repository: null
global:
  application_name: ayo_server
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
